# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppFactory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for AppFactory
	pod 'Firebase/Core', '4.0.0'
	pod 'FirebaseMessaging'

  target 'AppFactory-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
  end

  target 'AppFactoryTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase/Core', '4.0.0'
	pod 'FirebaseMessaging'
  end

end

target 'AppFactory-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppFactory-tvOS

end
